// Code generated by mockery v2.43.2. DO NOT EDIT.

package storagemocks

import (
	context "context"

	inventory "co.bastriguez/inventory/internal/inventory"
	mock "github.com/stretchr/testify/mock"
)

// ClientPersister is an autogenerated mock type for the ClientPersister type
type ClientPersister struct {
	mock.Mock
}

// Save provides a mock function with given fields: _a0, _a1
func (_m *ClientPersister) Save(_a0 context.Context, _a1 inventory.Client) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, inventory.Client) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewClientPersister creates a new instance of ClientPersister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClientPersister(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClientPersister {
	mock := &ClientPersister{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
