// Code generated by mockery v2.43.2. DO NOT EDIT.

package creatingmocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ClientCreator is an autogenerated mock type for the ClientCreator type
type ClientCreator struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, docType, docNumber, name
func (_m *ClientCreator) Create(ctx context.Context, docType string, docNumber string, name string) error {
	ret := _m.Called(ctx, docType, docNumber, name)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, docType, docNumber, name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewClientCreator creates a new instance of ClientCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClientCreator(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClientCreator {
	mock := &ClientCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
