// Code generated by mockery v2.43.2. DO NOT EDIT.

package commandmocks

import (
	context "context"

	command "co.bastriguez/inventory/kit/command"

	mock "github.com/stretchr/testify/mock"
)

// Bus is an autogenerated mock type for the Bus type
type Bus struct {
	mock.Mock
}

// DispatchCommand provides a mock function with given fields: _a0, _a1
func (_m *Bus) DispatchCommand(_a0 context.Context, _a1 command.Command) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for DispatchCommand")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, command.Command) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DispatchQuery provides a mock function with given fields: _a0, _a1
func (_m *Bus) DispatchQuery(_a0 context.Context, _a1 command.Query) (command.QueryResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for DispatchQuery")
	}

	var r0 command.QueryResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, command.Query) (command.QueryResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, command.Query) command.QueryResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(command.QueryResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, command.Query) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PublishEvent provides a mock function with given fields: _a0, _a1
func (_m *Bus) PublishEvent(_a0 context.Context, _a1 []command.Event) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for PublishEvent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []command.Event) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RegisterCommandHandler provides a mock function with given fields: _a0, _a1
func (_m *Bus) RegisterCommandHandler(_a0 command.Type, _a1 command.CommandHandler) {
	_m.Called(_a0, _a1)
}

// RegisterEventHandler provides a mock function with given fields: _a0, _a1
func (_m *Bus) RegisterEventHandler(_a0 command.Type, _a1 command.EventHandler) {
	_m.Called(_a0, _a1)
}

// RegisterQueryHandler provides a mock function with given fields: _a0, _a1
func (_m *Bus) RegisterQueryHandler(_a0 command.Type, _a1 command.QueryHandler) {
	_m.Called(_a0, _a1)
}

// NewBus creates a new instance of Bus. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBus(t interface {
	mock.TestingT
	Cleanup(func())
}) *Bus {
	mock := &Bus{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
